// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: yamul-backend-game.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	OpenGameStream(ctx context.Context, opts ...grpc.CallOption) (GameService_OpenGameStreamClient, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) OpenGameStream(ctx context.Context, opts ...grpc.CallOption) (GameService_OpenGameStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[0], "/game.GameService/openGameStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceOpenGameStreamClient{stream}
	return x, nil
}

type GameService_OpenGameStreamClient interface {
	Send(*StreamPackage) error
	Recv() (*StreamPackage, error)
	grpc.ClientStream
}

type gameServiceOpenGameStreamClient struct {
	grpc.ClientStream
}

func (x *gameServiceOpenGameStreamClient) Send(m *StreamPackage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServiceOpenGameStreamClient) Recv() (*StreamPackage, error) {
	m := new(StreamPackage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	OpenGameStream(GameService_OpenGameStreamServer) error
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) OpenGameStream(GameService_OpenGameStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenGameStream not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_OpenGameStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServiceServer).OpenGameStream(&gameServiceOpenGameStreamServer{stream})
}

type GameService_OpenGameStreamServer interface {
	Send(*StreamPackage) error
	Recv() (*StreamPackage, error)
	grpc.ServerStream
}

type gameServiceOpenGameStreamServer struct {
	grpc.ServerStream
}

func (x *gameServiceOpenGameStreamServer) Send(m *StreamPackage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServiceOpenGameStreamServer) Recv() (*StreamPackage, error) {
	m := new(StreamPackage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "openGameStream",
			Handler:       _GameService_OpenGameStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "yamul-backend-game.proto",
}
