package commands

type LoginDeniedReason byte

const (
	LoginDeniedReason_IncorrectUsernamePassword LoginDeniedReason = iota
	LoginDeniedReason_AccountAlreadyInUse
	LoginDeniedReason_AccountBlocked
	LoginDeniedReason_BadPassword
	LoginDeniedReason_CommunicationProblem
	LoginDeniedReason_IgrConcurrencyLimit
	LoginDeniedReason_IgrTimeLimit
	LoginDeniedReason_IgrGeneralFailure
)

type LoginDeniedCommand struct {
	Reason LoginDeniedReason
}
